### ISSUE TITLE
add

### ISSUE THREAD

**Issue by coco66688** [GaaraLabs/Gaara-Bot#5]
https://replit.com/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027

**Comment by MickySinghSahni** [comment]
well what should i suppose to do with this issues ? it's nowhere related to this project.

**Comment by DMONINK** [comment]
> https://replit.com/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027

well what should i suppose to do with this issues ? it's nowhere related to this project.
